#from node:12
FROM node:12-alpine


RUN apk add yarn
RUN yarn global add truffle


# Create app directory
WORKDIR /usr/node/app
COPY package*.json ./
RUN npm install
COPY . .

CMD [ "sh","-c", "truffle migrate && sleep 2000" ]
#CMD [ "truffle", "migrate" ]

